### ISSUE TITLE
NoMethodError: images method missing

### ISSUE THREAD

**Issue by shwanton** [cantino/ruby-readability#20]
Tying to get this working in a rails console with Ruby 1.9.3 and keep running into this error when I run:

```
source = open('http://www.economist.com/blogs/schumpeter/2012/02/greek-exit').read
Readability::Document.new(source).images

NoMethodError: undefined method `images' for Readability::Document
```

installed gems:
    ruby-readability (0.5.0)
    mini_magick (3.4)

When I run the readability specs w/ the same gemset, everything passes fine.
